rmarkdown::render("rank.Rmd", "html_document")
system("ls")
#system("mv  ~/Documents/R_with_git/Football/rank.html ~/Documents/github/robinkoetsier.github.io/")
system("cp -R  ~/Documents/R_with_git/Football/rank.html ~/Documents/github/robinkoetsier.github.io/")
setwd('~/Documents/github/robinkoetsier.github.io/')
system('git add .')
system('git commit -m "Add existing file"')
system('git push origin master')
setwd('~/Documents/R_with_git/Football/')
getwd()
